- name: install cassandra
  apt: name=cassandra state=latest

- name: override cassandra.yaml file
  template: src=cassandra.yaml dest=/etc/cassandra/

- name: make sure cassandra is enabled
  service: name=cassandra enabled=yes

- name: make sure cassandra is started
  service: name=cassandra state=running
