- template:
    src: templates/debug_host_vars.j2
    dest: /tmp/{{inventory_hostname}}_host_vars.json
- fetch:
    src: /tmp/{{inventory_hostname}}_host_vars.json
    dest: tmp/

- template:
    src: templates/debug_playbook_vars.j2
    dest: /tmp/{{inventory_hostname}}_playbook_vars.json
- fetch:
    src: /tmp/{{inventory_hostname}}_playbook_vars.json
    dest: tmp/
