---
- hosts: [ 'node1', 'node2']
  user: vagrant
  become: True
  tasks:
  - include_vars: vars/vagrant.yml
  # - include: tasks/debug.yml
  - include: tasks/repositories.yml
  - include: tasks/dependencies.yml
  - include: tasks/cassandra.yml
